import { readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync } from 'node:fs';
import { resolve, relative, dirname, join } from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';

const commit = 'b454cf80c5378d9d1ef846fe1c352e3068281b8d';
const source = resolve(process.argv[2] ?? '');
if (execFileSync('git', ['rev-parse', 'HEAD'], { cwd: source, encoding: 'utf8' }).trim() !== commit) {
  throw new Error(`Expected upstream commit ${commit}`);
}
const destination = resolve('src/vendor/uiarc');
const components = ['segmented-control', 'filter-toolbar', 'command-palette', 'combobox', 'date-range-picker', 'number-field', 'action-button', 'confirm-morph', 'inline-edit', 'bottom-sheet', 'animated-counter', 'metric-card', 'line-chart', 'donut-chart', 'sparkline', 'button'];
const paths = ['LICENSE', 'lib/motion-tokens.ts', 'registry/motion-tokens.ts', 'registry/foundation.css'];
for (const name of components) {
  for (const file of readdirSync(join(source, 'registry/components', name))) {
    paths.push(`registry/components/${name}/${file}`);
  }
}
const files = paths.sort().map(path => {
  const bytes = readFileSync(join(source, path));
  mkdirSync(dirname(join(destination, path)), { recursive: true });
  copyFileSync(join(source, path), join(destination, path));
  return { path, sha256: createHash('sha256').update(bytes).digest('hex') };
});
const upstreamPackage = JSON.parse(readFileSync(join(source, 'package.json'), 'utf8'));
writeFileSync(join(destination, 'provenance.json'), JSON.stringify({ repository: 'https://github.com/kuratlielia/arc-library', commit, license: 'MIT', components, files, upstreamRuntime: Object.fromEntries(['react', 'react-dom', 'motion', 'lucide-react', '@radix-ui/react-dialog'].map(name => [name, upstreamPackage.devDependencies[name]])), modifications: 'None. Source, CSS Modules and motion tokens are byte-for-byte copies. Build aliases resolve original imports. Foundation selectors are scoped in a separate generated stylesheet.' }, null, 2) + '\n');
const foundation = readFileSync(join(source, 'registry/foundation.css'), 'utf8');
const scopedFoundation = foundation
  .replaceAll(':root[data-theme="dark"]', '.dark .arc-runtime')
  .replaceAll(':root', '.arc-runtime')
  .replaceAll(':is(*:focus, *:focus-visible, *:focus-within)', '.arc-runtime :is(*:focus, *:focus-visible, *:focus-within)');
mkdirSync('src/styles', { recursive: true });
writeFileSync('src/styles/arc-foundation.scoped.css', '/* Generated by scripts/vendor-uiarc.mjs. Values are upstream; only selectors are scoped. */\n' + scopedFoundation + '\n.arc-runtime { color: var(--foreground); font-family: var(--font-body); --font-inter: "Inter"; --font-geist: "Geist"; }\n');
console.log(`Vendored ${files.length} unmodified source files at ${relative(process.cwd(), destination)}`);
